### ISSUE TITLE
HHInnerShadowView is highly inefficient

### ISSUE THREAD

**Issue by guykogus** [gloubibou/HHPanningTableViewCell#1]
I implemented this table view cell and tried it on an iPhone 4S, and it too a really long time to create this view. The <code>drawRect:</code> method was the culprit, according to instruments, and needs to be revised. I had to throw out this view in my implementation.

**Comment by gloubibou** [comment]
I remember having had an alternative implementation using a stretchable image. Unfortunately I cannot remember why I discarded that.

I would not worry too much about the performance of HHInnerShadowView. It is removed from the view tree once the drawer is hidden.

Since there usually is only one drawer revealed, there should be at most one HHInnerShadowView on screen at a given time.

**Comment by guykogus** [comment]
The issue is the creation of the view, which happens when a user swipes to reveal. On a device, swiping to reveal the drawer can take half a second, which is a noticeable delay.

**Comment by gloubibou** [comment]
That's odd. I don't see any delay when running ACTPrinter on an iPhone 4.

I'll see if I get test this on a 4S.

Thank you for reporting.

**Comment by guykogus** [comment]
Our drawer is a simple view - it contains an image view and 3 buttons. Somehow the inner shadow view's drawRect: method took a really long time.

**Comment by scheinem** [comment]
Hey,

I'm having the same problem using iOS 6 and iPhone 5. The swipee-to-reveal animation is stuttering. I gave it a try and removed the shadow then the animation was really smooth.

**Comment by gloubibou** [comment]
Hi!

I have replaced HHInnerShadowView with a more efficient implementation:
https://github.com/gloubibou/HHPanningTableViewCell/commit/4fa83f0ffdc371a8cd8275fb9441a70828ecc35a
